#Provided by @mrlesmithjr
#EveryThingShouldBeVirtual.com

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network"
  config.vm.network :forwarded_port, guest: 514, host: 1514, protocol: 'tcp'
  config.vm.network :forwarded_port, guest: 514, host: 1514, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 12900, host: 12900
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp'
  config.vm.provision :shell, path: "provision.sh"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "graylog2-server-1"
	vb.gui = true
    vb.memory = "2048"
    vb.cpus = "2"  
  end
end
