require ::File.join(::File.dirname(__FILE__), '../vagranthelper.rb')

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "dummy"
	config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
	config.omnibus.chef_version = '11.12.8'
	config.vm.synced_folder "../shared", "/vagrant"

	config.vm.provider :aws do |aws, override|
		aws_instance(aws, override, "ami-234ecc54","ubuntu", "Graylog-Ubuntu",false)
	end

	config.vm.provision "shell", inline: "#!/bin/bash\nsudo bash /vagrant/provision.sh ubuntu"
end
